<a href="https://colab.research.google.com/github/SYWoo02/Engineer_BigData_Analysis_10/blob/main/part1_11_~_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 11 슬라이싱, 사분위수, 결측치 제거

In [2]:
import pandas as pd
df11 = pd.read_csv('type1_data1.csv')
df11.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

## 1. 데이터에서 결측치가 있는 데이터(행)을 모두 제거하시오.

In [3]:
df_11 = df11.dropna()
df_11

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

## 2. 결측치가 제거된 데이터를 사용해 앞에서부터 70% 데이터를 구하시오. (단, 데이터 70% 지점의 값이 소수점으로 계산될 경우 소수점 이하는 버림)

In [4]:
df_11_70 = df_11.iloc[:int(len(df_11) * 0.7)]
df_11_70

       id   age city     f1  f2      f3    f4         f5  subscribed    views
2    id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5    id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7    id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9    id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10  id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
11   id11  40.0   서울   68.0   0    gold  ENFP  98.429899  2024-10-29   6752.0
13   id13  15.0   서울   68.0   0    gold  ESFJ  83.685380  2024-12-30   5643.0
14   id14  77.0   서울   50.0   1    gold  ENTJ  67.886373  2024-09-19   5700.0
15   id15  22.0   서울   67.0   1    gold  ENTP   9.796378  2024-05-26   7676.0
16   id16  68.0   서울   85.0   0    gold  ESFP  16.283854  2024-07-25   9472.0
18   id18  41.0   서울   87.0   2    gold  ISFJ  80.138280  2024-03-03   7933.0
22   id22  -6.3   부산   72.0   1    gold  ENFP  52.667078  2024-02-09   6147.0
23   id23  34.0   부산   75.0   1    gold  ISTP  69.730313  2024-05-21   6236.0
24   id24  80.0   부산   44.0   0    gold  INFJ  73.586397  2024-09-11   5976.0
26   id26  55.0   부산   57.0   1    gold  ENFP  83.685380  2024-05-01   5857.0
27   id27  37.0   부산   60.0   0  silver  ESTP  73.586397  2024-10-13   4255.0
28   id28  38.0   부산   34.0   1    gold  ENTP  80.138280  2024-10-31   5068.0
29   id29 -13.5   부산   47.0   2    gold  ENTP  67.886373  2024-08-28   6793.0
31   id31  86.0   부산   77.0   0    gold  ESFJ  73.586397  2024-02-11   8014.0
32   id32  25.0   부산   64.0   0     vip  ISFJ  13.049921  2024-05-24  17421.0
33   id33  47.0   부산   94.0   0  silver  ENFJ  17.252986  2024-04-02   3880.0
36   id36  68.0   부산   77.0   1    gold  INTP  13.049921  2024-07-20   9713.0
40   id40  56.0   대구   75.0   0    gold  ENFP  17.252986  2024-01-22   8481.0
41   id41  81.0   대구   55.0   0    gold  ENFJ  37.113739  2024-10-04   8640.0
42   id42  65.0   대구   48.0   2    gold  ESTP  33.308999  2024-02-09   5999.0
43   id43  23.0   대구   60.0   0  silver  ISTP  29.269869  2024-05-18   3878.0
45   id45  97.0   대구   88.0   0    gold  ENFJ  13.049921  2024-06-21   8317.0
47   id47  34.6   대구   75.0   1    gold  ESTJ  90.496999  2024-05-28   8628.0
49   id49  75.0   대구   88.0   0    gold  INTP  37.113739  2024-03-31   9737.0
52   id52  97.0   대구   82.0   1    gold  ISFJ  90.496999  2024-05-20   8518.0
53   id53  52.0   대구   50.0   0    gold  ESTP  20.129444  2024-09-09   7012.0
55   id55  75.0   대구   63.0   2    gold  ENTP  13.049921  2024-02-06   6042.0
57   id57   3.0   대구  111.0   0  silver  ISFJ  29.269869  2024-01-12   4421.0
63   id63  88.0   경기   86.0   1  silver  ISFJ  73.586397  2024-12-01   4053.0
64   id64  43.0   경기   62.0   2    gold  ESFP  73.586397  2024-02-22   5995.0
68   id68  35.0   경기   45.0   2    gold  ISFP  67.886373  2024-07-29   8599.0
70   id70  -9.0   경기   96.0   1  silver  ISTP  48.431184  2024-11-17   4442.0
71   id71  35.0   경기   84.0   2    gold  ISFP  52.667078  2024-07-15   8087.0
74   id74  45.0   경기   98.0   0    gold  ESTP  52.667078  2024-05-27   7739.0
75   id75  63.0   경기   47.0   0    gold  ESTP  20.129444  2024-06-12   6779.0
78   id78  92.0   경기   96.0   1    gold  INTJ  69.730313  2024-10-27   7565.0
80   id80  67.0   경기   60.0   0  silver  ISFP  83.685380  2024-01-14   4381.0
83   id83  73.0   경기   50.0   1     vip  ENTP  80.138280  2024-09-26  19139.0
84   id84  66.0   경기   44.0   0    gold  INTP  83.685380  2024-12-19   5650.0
85   id85  83.6   경기   55.0   0    gold  INFJ  80.138280  2024-09-24   6719.0
89   id89  34.0   경기   66.0   1    gold  ENTJ  33.308999  2024-10-14   6119.0
91   id91   6.0   경기   72.0   0    gold  INTP   9.796378  2024-08-23   8988.0
92   id92  97.0   경기   78.0   1    gold  INFP  97.381034  2024-05-08   9625.0
95   id95  77.0   경기   43.0   1    gold  INTJ  91.297791  2024-05-21   8697.0

## 3. 앞에서 구한 70% 데이터 중 'views' 칼럼의 3사분위수에서 1사분위수를 뺀 값을 정수로 구하시오.

In [5]:
result = df_11_70['views'].quantile(0.75) - df_11_70['views'].quantile(0.25)
print(int(result))

2771

# Section 12 결측치 처리, 최빈값, 데이터 개수

In [42]:
import pandas as pd
df12 = pd.read_csv('type1_data1.csv')

## 1. 결측치가 가장 많은 두 컬럼을 찾으시오.

In [43]:
missing = df12.isnull().sum()
missing = missing.sort_values(ascending=False)
print(missing.index[:2])

Index(['f1', 'f3'], dtype='object')

## 2. 첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.

In [44]:
df12 = df12.dropna(subset = ['f1'])

## 3. 두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.

In [45]:
freq = df12['f3'].mode()[0]
df12['f3'] = df12['f3'].fillna(freq)

## 4. 'f3' 컬럼의 'gold' 값을 가진 데이터의 수를 정수형으로 구하시오.

In [49]:
cond = df12['f3'] == 'gold'
print(len(df12[cond]))

63

# Section 13 결측 데이터 찾기, 필터링, 평균값

In [58]:
import pandas as pd
df13 = pd.read_csv('type1_data1.csv')

## 1. 'f1' 컬럼에 결측치가 있는 데이터만 선택하시오.

In [59]:
f1_missing = df13['f1'].isnull()
df_13_f1_missing = df13[f1_missing]

## 2. 선택된 데이터에서 'age' 컬럼의 평균값을 구하시오. (반올림 후 소수 첫째 자리까지 계산)

In [61]:
mean = df_13_f1_missing['age'].mean()
print(round(mean,1))

53.6

# Section 14 중복 데이터 제거, 값 변경, 데이터 개수

In [81]:
import pandas as pd
import numpy as np
df14 = pd.read_csv('type1_data1.csv')

## 1. 중복 데이터를 제거하시오.

In [82]:
df_14 = df14.drop_duplicates()
df_14.head(5)

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

## 2. 'f3' 컬럼의 결측치는 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.

In [83]:
# 방법 1
df_14['f3'] = df_14['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)
df_14.head(5)

<ipython-input-83-357c990efd36>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_14['f3'] = df_14['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)
<ipython-input-83-357c990efd36>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_14['f3'] = df_14['f3'].replace(np.nan,0).replace('silver',1).replace('gold',2).replace('vip',3)

     id   age city    f1  f2  f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0   2  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   0  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1   2  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   0  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   0  ISFJ  29.269869  2024-03-07  1338.0

In [85]:
# 방법 2
df_14 = df_14.fillna(0)
df_14['f3'] = df_14['f3'].map({'silver':1, 'gold' : 2, 'vip': 3})
df_14.head(5)

     id   age city    f1  f2  f3    f4         f5  subscribed   views
0  id01   2.0   서울   0.0   0 NaN  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1 NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1 NaN  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   0.0   2 NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2 NaN  ISFJ  29.269869  2024-03-07  1338.0

## 3. 변환된 'f3' 컬럼의 총합을 정수형으로 구하시오.

In [84]:
sum = df_14['f3'].sum()
print(int(sum))

167

# Section 15 컬럼 삭제, 행 단위 합계, 필터링

In [166]:
import pandas as pd
df15 = pd.read_csv('type1_data1.csv')

## 1. 주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.

In [167]:
df_15 = df15.select_dtypes(exclude='object')
df_15.head(5)

    age    f1  f2         f5   views
0   2.0   NaN   0  91.297791  6820.0
1   9.0  70.0   1  60.339826  2534.0
2  27.0  61.0   1  17.252986  7312.0
3  75.0   NaN   2  52.667078   493.0
4  24.0  85.0   2  29.269869  1338.0

## 2. 숫자 자료형 컬럼의 결측치를 0으로 대체하시오.

In [168]:
df_15.isnull().sum()

age       0
f1       31
f2        0
f5        0
views     4
dtype: int64

In [169]:
df_15 = df_15.fillna(0)
df_15.head(5)

    age    f1  f2         f5   views
0   2.0   0.0   0  91.297791  6820.0
1   9.0  70.0   1  60.339826  2534.0
2  27.0  61.0   1  17.252986  7312.0
3  75.0   0.0   2  52.667078   493.0
4  24.0  85.0   2  29.269869  1338.0

## 3. 각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오.
(각 행의 합: 'age' + 'f1' + 'f2' + 'f5' + 'views')

In [173]:
df_15 = df_15.T
df_15

      age    f1   f2         f5   views
0     2.0   0.0  0.0  91.297791  6820.0
1     9.0  70.0  1.0  60.339826  2534.0
2    27.0  61.0  1.0  17.252986  7312.0
3    75.0   0.0  2.0  52.667078   493.0
4    24.0  85.0  2.0  29.269869  1338.0
..    ...   ...  ...        ...     ...
115  22.0  23.0  0.0   0.000000  9747.0
116  23.0  65.0  0.0   0.000000  5628.0
117  23.0  12.0  1.0   0.000000  1267.0
118  23.0  65.0  2.0   0.000000  6543.0
119  24.0  94.0  1.0   0.000000  2356.0

[120 rows x 5 columns]

In [177]:
# 각 행의 합 계산
row_sums = df_15.sum(axis=1)

# 합이 3000보다 큰 행의 개수
count_over_3000 = (row_sums > 3000).sum()

# 결과 출력
print(int(count_over_3000))

88