<a href="https://colab.research.google.com/github/SYWoo02/Engineer_BigData_Analysis_10/blob/main/part1_31_~_39.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 31 문자열, 형 변환

In [3]:
import pandas as pd
df31 = pd.read_csv("delivery_time.csv")
df31

,주문시간,실제도착시간,예상도착시간,앱종류,거리,결제종류,user
0,2023-07-26 08:05:49,2023-07-26 09:14:06,2023-07-26 08:39:42,여기여,1.93,카드,user_275
1,2022-11-07 10:21:54,2022-11-07 10:44:04,2022-11-07 10:50:15,배고팡,5.19,카드,user_360
2,2023-04-18 05:00:57,2023-04-18 06:12:46,2023-04-18 05:32:53,배고팡,13.85,카드,user_36
3,2023-08-18 10:46:28,2023-08-18 11:16:25,2023-08-18 11:08:33,배고팡,10.90,앱결제,user_65
4,2023-08-11 09:58:27,2023-08-11 11:27:57,2023-08-11 10:51:57,여기여,14.96,카드,user_176
...,...,...,...,...,...,...,...
995,2022-10-10 03:13:30,2022-10-10 04:13:48,2022-10-10 04:15:37,배고팡,1.79,현금,user_186
996,2023-02-03 12:47:19,2023-02-03 13:11:46,2023-02-03 13:12:57,배고팡,15.55,카드,user_239
997,2023-01-05 21:28:58,2023-01-05 21:57:41,2023-01-05 21:57:44,배고팡,8.33,현금,user_264
998,2023-06-15 03:56:42,2023-06-15 04:14:24,2023-06-15 04:18:38,여기여,8.20,앱결제,user_229
999,2023-08-02 20:53:53,2023-08-02 22:04:06,2023-08-02 22:09:22,여기여,5.33,카드,user_148

## 1. 'user' 컬럼에서 user 뒤에 있는 숫자 값만 추출하시오.

In [4]:
df31['user_int'] = df31['user'].str[5:]
df31['user_int']

0      275
1      360
2       36
3       65
4      176
      ...
995    186
996    239
997    264
998    229
999    148
Name: user_int, Length: 1000, dtype: object

## 2. 추출된 숫자 값을 모두 합한 값을 정수로 구하시오.

In [5]:
# 추출된 숫자값들이 들어있는 데이터프레임의 type은 string
# str -> int로 형변환 필요 (astype() 이용)
df31['user_int'] = df31['user_int'].astype('int')

# 결과출력
sum = df31['user_int'].sum()
print(sum)

261387

# Section 32 합계(열 방향), 상위 값 선택

In [6]:
df32 = pd.read_csv("school_data.csv")
df32

      이름  수학   영어  국어 수학교사 영어교사 국어교사
0    강아지  66   61  26  김선생  장선생  최선생
1    고양이  92   48  80  김선생  장선생  이선생
2     토끼  98    7   6  김선생  장선생  최선생
3     사자  17   99  14  김선생  유선생  최선생
4    호랑이  83   92  75  박선생  장선생  이선생
5      곰  57   52  54  김선생  유선생  이선생
6    원숭이  86   97  71  김선생  장선생  이선생
7     기린  97   85   1  김선생  유선생  최선생
8    코끼리  96   94  43  김선생  유선생  이선생
9     판다  47   27  58  박선생  장선생  이선생
10    늑대  73   34  55  박선생  장선생  최선생
11    여우  32   97  25  박선생  유선생  이선생
12    펭귄  46   76  50  김선생  장선생  이선생
13  하이에나  96   40  84  김선생  장선생  최선생
14   코알라  25    3  56  박선생  장선생  이선생
15    강치  83   69  49  박선생  유선생  이선생
16   햄스터  78   64  12  김선생  장선생  최선생
17     뱀  36   75  18  김선생  장선생  이선생
18   독수리  96   34  81  박선생  장선생  이선생
19   침팬지  80   58   1  박선생  장선생  이선생
20    하마  68   10  51  박선생  유선생  이선생
21   두더지  49   22  44  김선생  유선생  최선생
22    물소  55   77  48  박선생  장선생  이선생
23   캥거루  67   18  56  김선생  장선생  최선생
24    참새   2  100  91  김선생  유선생  최선생
25    타조  84   15  49  박선생  유선생  이선생
26   개구리  39   27  86  박선생  장선생  이선생
27   펠리칸  66   30   3  김선생  유선생  이선생
28   돌고래  84   52  67  박선생  유선생  최선생
29     매  47   70  11  김선생  유선생  이선생

## 1. 수학, 영어, 국어 점수의 합을 구하시오.

In [7]:
df32['총 점수'] = df32['수학'] + df32['영어'] + df32['국어']
df32['총 점수']

0     153
1     220
2     111
3     130
4     250
5     163
6     254
7     183
8     233
9     132
10    162
11    154
12    172
13    220
14     84
15    201
16    154
17    129
18    211
19    139
20    129
21    115
22    180
23    141
24    193
25    148
26    152
27     99
28    203
29    128
Name: 총 점수, dtype: int64

## 2. 합이 가장 큰 상위 10명을 찾으시오.

In [8]:
top10 = df32.sort_values('총 점수', ascending=False).head(10)
top10

      이름  수학   영어  국어 수학교사 영어교사 국어교사  총 점수
6    원숭이  86   97  71  김선생  장선생  이선생   254
4    호랑이  83   92  75  박선생  장선생  이선생   250
8    코끼리  96   94  43  김선생  유선생  이선생   233
13  하이에나  96   40  84  김선생  장선생  최선생   220
1    고양이  92   48  80  김선생  장선생  이선생   220
18   독수리  96   34  81  박선생  장선생  이선생   211
28   돌고래  84   52  67  박선생  유선생  최선생   203
15    강치  83   69  49  박선생  유선생  이선생   201
24    참새   2  100  91  김선생  유선생  최선생   193
7     기린  97   85   1  김선생  유선생  최선생   183

## 3. 찾은 10명의 수학 평균 점수를 구하시오. (반올림 후 정수 출력)

In [9]:
math_mean = top10['수학'].mean()
print(round(math_mean))

82

# Section 33 데이터프레임 재구조화

In [10]:
df33 = pd.read_csv("school_data.csv")
df33

      이름  수학   영어  국어 수학교사 영어교사 국어교사
0    강아지  66   61  26  김선생  장선생  최선생
1    고양이  92   48  80  김선생  장선생  이선생
2     토끼  98    7   6  김선생  장선생  최선생
3     사자  17   99  14  김선생  유선생  최선생
4    호랑이  83   92  75  박선생  장선생  이선생
5      곰  57   52  54  김선생  유선생  이선생
6    원숭이  86   97  71  김선생  장선생  이선생
7     기린  97   85   1  김선생  유선생  최선생
8    코끼리  96   94  43  김선생  유선생  이선생
9     판다  47   27  58  박선생  장선생  이선생
10    늑대  73   34  55  박선생  장선생  최선생
11    여우  32   97  25  박선생  유선생  이선생
12    펭귄  46   76  50  김선생  장선생  이선생
13  하이에나  96   40  84  김선생  장선생  최선생
14   코알라  25    3  56  박선생  장선생  이선생
15    강치  83   69  49  박선생  유선생  이선생
16   햄스터  78   64  12  김선생  장선생  최선생
17     뱀  36   75  18  김선생  장선생  이선생
18   독수리  96   34  81  박선생  장선생  이선생
19   침팬지  80   58   1  박선생  장선생  이선생
20    하마  68   10  51  박선생  유선생  이선생
21   두더지  49   22  44  김선생  유선생  최선생
22    물소  55   77  48  박선생  장선생  이선생
23   캥거루  67   18  56  김선생  장선생  최선생
24    참새   2  100  91  김선생  유선생  최선생
25    타조  84   15  49  박선생  유선생  이선생
26   개구리  39   27  86  박선생  장선생  이선생
27   펠리칸  66   30   3  김선생  유선생  이선생
28   돌고래  84   52  67  박선생  유선생  최선생
29     매  47   70  11  김선생  유선생  이선생

## 1. 과목에 상관없이 점수가 가장 작은 점수 25개를 찾으시오.

In [11]:
# 이름을 유지하면서 수학, 영어, 국어 형태 변경 (열 -> 행)
melted_df33 = df33.melt(id_vars=['이름'], value_vars=['수학','영어','국어'])
melted_df33

     이름 variable  value
0   강아지       수학     66
1   고양이       수학     92
2    토끼       수학     98
3    사자       수학     17
4   호랑이       수학     83
..  ...      ...    ...
85   타조       국어     49
86  개구리       국어     86
87  펠리칸       국어      3
88  돌고래       국어     67
89    매       국어     11

[90 rows x 3 columns]

## 2. 찾은 점수 25개의 합을 정수로 구하시오.

In [12]:
res = melted_df33['value'].nsmallest(25).sum()
print(res)

420

# Section 34 데이터 합치기(concat)

In [13]:
df34 = pd.read_csv("school_data.csv")
df34_science = pd.read_csv("school_data_science.csv")
df34_science

      이름  과학 과학교사
0    강아지  66  황선생
1    고양이  92  임선생
2     토끼  98  황선생
3     사자  17  임선생
4    호랑이  83  임선생
5      곰  57  임선생
6    원숭이  86  황선생
7     기린  97  황선생
8    코끼리  96  황선생
9     판다  47  황선생
10    늑대  73  임선생
11    여우  32  임선생
12    펭귄  46  황선생
13  하이에나  96  황선생
14   코알라  25  임선생
15    강치  83  황선생
16   햄스터  78  임선생
17     뱀  36  황선생
18   독수리  96  황선생
19   침팬지  80  임선생
20    하마  68  황선생
21   두더지  49  임선생
22    물소  55  황선생
23   캥거루  67  임선생
24    참새   2  황선생
25    타조  84  황선생
26   개구리  39  황선생
27   펠리칸  66  황선생
28   돌고래  84  임선생
29     매  47  황선생

## 1. 주어진 두 csv파일을 학생 순서를 기준으로 병합하시오. (단, 두 파일의 학생 순서는 동일하다.)

In [14]:
# 두 파일 병합 (열로 ; axis = 1)
new_df34 = pd.concat([df34, df34_science], axis=1)
new_df34

      이름  수학   영어  국어 수학교사 영어교사 국어교사    이름  과학 과학교사
0    강아지  66   61  26  김선생  장선생  최선생   강아지  66  황선생
1    고양이  92   48  80  김선생  장선생  이선생   고양이  92  임선생
2     토끼  98    7   6  김선생  장선생  최선생    토끼  98  황선생
3     사자  17   99  14  김선생  유선생  최선생    사자  17  임선생
4    호랑이  83   92  75  박선생  장선생  이선생   호랑이  83  임선생
5      곰  57   52  54  김선생  유선생  이선생     곰  57  임선생
6    원숭이  86   97  71  김선생  장선생  이선생   원숭이  86  황선생
7     기린  97   85   1  김선생  유선생  최선생    기린  97  황선생
8    코끼리  96   94  43  김선생  유선생  이선생   코끼리  96  황선생
9     판다  47   27  58  박선생  장선생  이선생    판다  47  황선생
10    늑대  73   34  55  박선생  장선생  최선생    늑대  73  임선생
11    여우  32   97  25  박선생  유선생  이선생    여우  32  임선생
12    펭귄  46   76  50  김선생  장선생  이선생    펭귄  46  황선생
13  하이에나  96   40  84  김선생  장선생  최선생  하이에나  96  황선생
14   코알라  25    3  56  박선생  장선생  이선생   코알라  25  임선생
15    강치  83   69  49  박선생  유선생  이선생    강치  83  황선생
16   햄스터  78   64  12  김선생  장선생  최선생   햄스터  78  임선생
17     뱀  36   75  18  김선생  장선생  이선생     뱀  36  황선생
18   독수리  96   34  81  박선생  장선생  이선생   독수리  96  황선생
19   침팬지  80   58   1  박선생  장선생  이선생   침팬지  80  임선생
20    하마  68   10  51  박선생  유선생  이선생    하마  68  황선생
21   두더지  49   22  44  김선생  유선생  최선생   두더지  49  임선생
22    물소  55   77  48  박선생  장선생  이선생    물소  55  황선생
23   캥거루  67   18  56  김선생  장선생  최선생   캥거루  67  임선생
24    참새   2  100  91  김선생  유선생  최선생    참새   2  황선생
25    타조  84   15  49  박선생  유선생  이선생    타조  84  황선생
26   개구리  39   27  86  박선생  장선생  이선생   개구리  39  황선생
27   펠리칸  66   30   3  김선생  유선생  이선생   펠리칸  66  황선생
28   돌고래  84   52  67  박선생  유선생  최선생   돌고래  84  임선생
29     매  47   70  11  김선생  유선생  이선생     매  47  황선생

## 2. 학생별로 수학, 영어, 국어, 과학 점수의 평균을 구하시오.

In [15]:
new_df34['과목 평균'] = (new_df34['수학'] + new_df34['영어'] + new_df34['국어'] + new_df34['과학']) / 4
new_df34['과목 평균']

0     54.75
1     78.00
2     52.25
3     36.75
4     83.25
5     55.00
6     85.00
7     70.00
8     82.25
9     44.75
10    58.75
11    46.50
12    54.50
13    79.00
14    27.25
15    71.00
16    58.00
17    41.25
18    76.75
19    54.75
20    49.25
21    41.00
22    58.75
23    52.00
24    48.75
25    58.00
26    47.75
27    41.25
28    71.75
29    43.75
Name: 과목 평균, dtype: float64

## 3. 평균 점수가 60점 이상인 인원 수를 계산하시오.

In [16]:
count = (new_df34['과목 평균'] >= 60).sum()
print(count)

9

# Section 35 데이터합치기 (merge)

In [17]:
df35 = pd.read_csv("school_data.csv")
df35_social = pd.read_csv("school_data_social.csv")
df35_social

      이름   사회 사회교사
0     기린   47  오선생
1      매   61  우선생
2      곰   48  우선생
3    개구리    7  오선생
4    코끼리   99  오선생
5    펠리칸   92  오선생
6     펭귄   52  오선생
7    두더지   97  우선생
8     여우   85  오선생
9    캥거루   94  우선생
10   독수리   27  우선생
11   호랑이   34  오선생
12    사자   97  우선생
13    참새   76  우선생
14   햄스터   40  우선생
15   코알라    3  오선생
16    하마   69  우선생
17    판다   64  우선생
18    강치   75  우선생
19    타조   34  오선생
20   강아지   58  오선생
21   고양이   10  오선생
22    물소   22  우선생
23    늑대   77  오선생
24   침팬지   18  오선생
25     뱀  100  우선생
26   원숭이   15  우선생
27   돌고래   27  우선생
28    토끼   30  오선생
29  하이에나   52  우선생

## 1. 두 파일을 '이름을 기준으로 합치시오.

In [18]:
# 이름을 기준으로 두 파일 병합
new_df35 = pd.merge(df35, df35_social, on='이름')
new_df35

      이름  수학   영어  국어 수학교사 영어교사 국어교사   사회 사회교사
0    강아지  66   61  26  김선생  장선생  최선생   58  오선생
1    고양이  92   48  80  김선생  장선생  이선생   10  오선생
2     토끼  98    7   6  김선생  장선생  최선생   30  오선생
3     사자  17   99  14  김선생  유선생  최선생   97  우선생
4    호랑이  83   92  75  박선생  장선생  이선생   34  오선생
5      곰  57   52  54  김선생  유선생  이선생   48  우선생
6    원숭이  86   97  71  김선생  장선생  이선생   15  우선생
7     기린  97   85   1  김선생  유선생  최선생   47  오선생
8    코끼리  96   94  43  김선생  유선생  이선생   99  오선생
9     판다  47   27  58  박선생  장선생  이선생   64  우선생
10    늑대  73   34  55  박선생  장선생  최선생   77  오선생
11    여우  32   97  25  박선생  유선생  이선생   85  오선생
12    펭귄  46   76  50  김선생  장선생  이선생   52  오선생
13  하이에나  96   40  84  김선생  장선생  최선생   52  우선생
14   코알라  25    3  56  박선생  장선생  이선생    3  오선생
15    강치  83   69  49  박선생  유선생  이선생   75  우선생
16   햄스터  78   64  12  김선생  장선생  최선생   40  우선생
17     뱀  36   75  18  김선생  장선생  이선생  100  우선생
18   독수리  96   34  81  박선생  장선생  이선생   27  우선생
19   침팬지  80   58   1  박선생  장선생  이선생   18  오선생
20    하마  68   10  51  박선생  유선생  이선생   69  우선생
21   두더지  49   22  44  김선생  유선생  최선생   97  우선생
22    물소  55   77  48  박선생  장선생  이선생   22  우선생
23   캥거루  67   18  56  김선생  장선생  최선생   94  우선생
24    참새   2  100  91  김선생  유선생  최선생   76  우선생
25    타조  84   15  49  박선생  유선생  이선생   34  오선생
26   개구리  39   27  86  박선생  장선생  이선생    7  오선생
27   펠리칸  66   30   3  김선생  유선생  이선생   92  오선생
28   돌고래  84   52  67  박선생  유선생  최선생   27  우선생
29     매  47   70  11  김선생  유선생  이선생   61  우선생

## 2. 영어교사가 장선생이면서 사회교사가 오선생인 학생들을 필터링하시오.

In [19]:
cond1 = new_df35['영어교사'] == '장선생'
cond2 = new_df35['사회교사'] == '오선생'
filtered_new_df35 = new_df35[cond1 & cond2]
filtered_new_df35

     이름  수학  영어  국어 수학교사 영어교사 국어교사  사회 사회교사
0   강아지  66  61  26  김선생  장선생  최선생  58  오선생
1   고양이  92  48  80  김선생  장선생  이선생  10  오선생
2    토끼  98   7   6  김선생  장선생  최선생  30  오선생
4   호랑이  83  92  75  박선생  장선생  이선생  34  오선생
10   늑대  73  34  55  박선생  장선생  최선생  77  오선생
12   펭귄  46  76  50  김선생  장선생  이선생  52  오선생
14  코알라  25   3  56  박선생  장선생  이선생   3  오선생
19  침팬지  80  58   1  박선생  장선생  이선생  18  오선생
26  개구리  39  27  86  박선생  장선생  이선생   7  오선생

## 3. 필터링된 학생들의 수학 점수를 모두 더한 후 정수로 구하시오.

In [20]:
total_math = filtered_new_df35['수학'].sum()
print(total_math)

602

# Section 36 조건별 변환(transform)

In [21]:
df36 = pd.read_csv("sales.csv")
df36

    지역코드  거래ID    판매금액
0    101  T001  1000.0
1    101  T002  1200.0
2    101  T003     NaN
3    101  T004  1500.0
4    101  T005  1100.0
5    102  T006  2000.0
6    102  T007  2500.0
7    102  T008  2300.0
8    102  T009     NaN
9    102  T010  2100.0
10   103  T011  3000.0
11   103  T012  3500.0
12   103  T013  3200.0
13   103  T014  4000.0
14   103  T015     NaN

## 1. 결측된 판매금액은 해당 지역의 평균 판매금액으로 결측값을 대체하시오.

In [22]:
df36.isnull().sum()

지역코드    0
거래ID    0
판매금액    3
dtype: int64

In [23]:
df36  = df36.fillna(df36['판매금액'].mean())
df36.isnull().sum()

지역코드    0
거래ID    0
판매금액    0
dtype: int64

## 2. 각 거래마다 "판매금액"과 해당 지역의 평균 판매금액의 "차이"를 절대값으로 구하시오.

In [24]:
# 해당 지역의 평균 판매금액
# pd.transform(): 그룹별로 계산된 결과를 원래 데이터의 형태(행 수)를 유지하면서 반환할 때 사용
df36['지역평균'] = df36.groupby(by='지역코드')['판매금액'].transform('mean')

# 각 거래별 판매 금액과 해당 지역의 평균 판매금액의 차이 (절대값)
df36['차이'] = abs(df36['판매금액'] - df36['지역평균'])

df36['차이']

0     416.666667
1     216.666667
2     866.666667
3      83.333333
4     316.666667
5     236.666667
6     263.333333
7      63.333333
8      46.666667
9     136.666667
10    196.666667
11    303.333333
12      3.333333
13    803.333333
14    913.333333
Name: 차이, dtype: float64

## 3. 각 지역에서 차이값의 평균을 구한 후, 이 값이 가장 큰 지역의 지역코드를 구하시오.

In [25]:
# 지역별 차이값의 평균을 구함 -> idxmax()로 그 값이 가장 큰 지역의 지역코드 출력
result = df36.groupby(by='지역코드')['차이'].mean().idxmax()
print(result)

103

# Section 37 재구조화(unstack), 맵핑

In [35]:
df37 = pd.read_csv("store_sales.csv")
df37

   매장코드 요일  판매수량    단가
0     A  월    10  2000
1     A  화    15  1500
2     A  토    28  3332
3     B  월     5  2500
4     B  금     8  2200
5     B  일    17  2999
6     C  수    20  1800
7     C  목    25  1600
8     C  토    42  3554
9     C  일    49  3443
10    D  월    18  2100
11    D  토    31  3221
12    D  일    33  3110
13    E  화    10  1700
14    E  금    14  1900
15    E  토    32  2990
16    E  일    31  3276

## 1. 각 행에서 판매수량과 단가를 이용하여 매출액을 계산하시오.

In [36]:
df37['매출액'] = df37['판매수량'] * df37['단가']
df37['매출액']

0      20000
1      22500
2      93296
3      12500
4      17600
5      50983
6      36000
7      40000
8     149268
9     168707
10     37800
11     99851
12    102630
13     17000
14     26600
15     95680
16    101556
Name: 매출액, dtype: int64

## 2. 요일을 평일과 주말로 구분하고, 매장별 평일과 주말 매출액 합계를 구하시오.

In [39]:
# 요일을 평일과 주말로 구분 (map() 이용)
day_mapping = {'월':'평일', '화':'평일', '수':'평일', '목':'평일', '금':'평일', '토':'주말', '일':'주말'}
df37['구분'] = df37['요일'].map(day_mapping)

# 매장별 평일과 주말 매출액 합계 계산
sales_by_days_branch = df37.groupby(by=['매장코드','구분'])['매출액'].sum()
sales_by_days_branch

매장코드  구분
A     주말     93296
      평일     42500
B     주말     50983
      평일     30100
C     주말    317975
      평일     76000
D     주말    202481
      평일     37800
E     주말    197236
      평일     43600
Name: 매출액, dtype: int64

## 3. 매장별 평일과 주말 매출액 차이를 절대값으로 구하시오. 이후, 모든 매장 중 가장 큰 절대값 차이를 찾으시오.

In [42]:
# unstack(): 데이터프레임의 행 인덱스를 열 인덱스로 변환
df37_ = sales_by_days_branch.unstack()

df37_['평일-주말 간 매출차이'] = abs(df37_['주말'] - df37_['평일'])
max = df37_['평일-주말 간 매출차이'].max()
print(max)

241975

In [44]:
sales_by_days_branch

매장코드  구분
A     주말     93296
      평일     42500
B     주말     50983
      평일     30100
C     주말    317975
      평일     76000
D     주말    202481
      평일     37800
E     주말    197236
      평일     43600
Name: 매출액, dtype: int64

In [43]:
df37_

구분        주말     평일  평일-주말 간 매출차이
매장코드
A      93296  42500         50796
B      50983  30100         20883
C     317975  76000        241975
D     202481  37800        164681
E     197236  43600        153636

# Section 38 피벗테이블

In [45]:
df38 = pd.read_csv("region_sales.csv")
df38

          Date Region Product  Channel  Sales
0   2025-01-05  North       A   Online    120
1   2025-01-07  South       A  Offline    150
2   2025-02-10  North       B   Online    200
3   2023-02-12  North       A   Online    130
4   2025-03-15   East       A  Offline    100
5   2025-03-20  South       B   Online    170
6   2025-04-10  North       A  Offline    140
7   2023-04-12  North       B  Offline    180
8   2025-05-15   East       B   Online    210
9   2025-05-20  South       A   Online    160
10  2025-06-10  North       A   Online    190
11  2023-06-15  North       B   Online    220
12  2025-07-01   West       A  Offline    110
13  2025-07-05   West       B   Online    130
14  2025-07-10  South       B  Offline    145
15  2023-07-12   East       B  Offline    105
16  2025-07-13   East       A   Online    205
17  2025-07-14   West       B  Offline    115
18  2025-07-15   West       A   Online    135

## 1. 각 Region과 Channel 조합별로 제품(Product) A, B의 총 판매액을 계산하시오.

In [ ]:
# pd.pivot_table(
#     data,
#     values=None,         # 집계 대상 열
#     index=None,          # 행 인덱스로 사용할 열
#     columns=None,        # 열 인덱스로 사용할 열
#     aggfunc='mean',      # 집계 함수: 기본은 평균(mean)
#     fill_value=None      # 결측값 대체 값
# )

In [50]:
df38_ = pd.pivot_table(
    df38,
    values='Sales',         # 집계 대상 열
    index=['Region','Channel'],          # 행 인덱스로 사용할 열
    columns='Product',        # 열 인덱스로 사용할 열
    aggfunc='sum',      # 집계 함수: 기본은 평균(mean)
    fill_value=None      # 결측값 대체 값
)
df38_

Product           A    B
Region Channel
East   Offline  100  105
       Online   205  210
North  Offline  140  180
       Online   440  420
South  Offline  150  145
       Online   160  170
West   Offline  110  115
       Online   135  130

## 2. 제품 A의 매출 비율(A비율)을 구하시오. A비율 = (제품 A 판매액) / (제품 A 판매액 + 제품 B 판매액)

In [53]:
df38_['A_rate']= df38_['A'] / (df38_['A'] + df38_['B'])
df38_['B_rate']= df38_['B'] / (df38_['A'] + df38_['B'])
df38_

Product           A    B    A_rate    B_rate
Region Channel
East   Offline  100  105  0.487805  0.512195
       Online   205  210  0.493976  0.506024
North  Offline  140  180  0.437500  0.562500
       Online   440  420  0.511628  0.488372
South  Offline  150  145  0.508475  0.491525
       Online   160  170  0.484848  0.515152
West   Offline  110  115  0.488889  0.511111
       Online   135  130  0.509434  0.490566

## 3. A비율 중 최댓값을 찾아 반올림하여 소수 둘째 자리까지 구하시오.

In [54]:
max = df38_['A_rate'].max()
print(round(max,2))

0.51

# Section 39 재구조화(melt), 그룹핑

In [62]:
df39 = pd.read_csv("monthly_sales.csv")
df39.describe()

              Jan         Feb         Mar
count   50.000000   50.000000   50.000000
mean   134.880000  138.100000  143.900000
std     33.147561   31.478694   32.098223
min     80.000000   85.000000   88.000000
25%    105.750000  110.000000  116.250000
50%    136.000000  135.000000  146.500000
75%    160.000000  163.750000  170.000000
max    200.000000  192.000000  195.000000

In [58]:
df39.head(5)

  Region  Jan  Feb  Mar
0  Seoul  120  135  110
1  Seoul   95  108  145
2  Seoul  200  179  140
3  Seoul  150  155  170
4  Seoul  110   98  190

In [59]:
df39.tail(5)

     Region  Jan  Feb  Mar
45  Daejeon  150  155  170
46  Daejeon  120  105  115
47  Daejeon  130  135  140
48  Daejeon   95   98  105
49  Daejeon  155  160  175

## 1. 지역(Region)과 월(Jan, Feb, Mar)별 매출(Sales) 합계를 구하시오.

In [ ]:
# pd.melt(
#     frame,                         # 변환할 데이터프레임
#     id_vars=None,                  # 그대로 유지할 열
#     value_vars=None,               # 녹일 열들 (default: 나머지 전부)
#     var_name='variable',           # 녹인 열 이름
#     value_name='value'             # 녹인 값 이름
# )
# 열 -> 행

In [80]:
# Region열만 남기고 월(Jan, Feb, Mar)열들을 melt(열 -> 행)
melted_df39 = pd.melt(df39,id_vars='Region')
# melted_df39

# Region과 variable(월) 별 value(매출) 합계 계산
total_Sales = melted_df39.groupby(by=['Region','variable'])['value'].sum()
total_Sales

Region   variable
Busan    Feb         1323
         Jan         1256
         Mar         1371
Daegu    Feb         1365
         Jan         1317
         Mar         1538
Daejeon  Feb         1348
         Jan         1350
         Mar         1400
Incheon  Feb         1444
         Jan         1436
         Mar         1466
Seoul    Feb         1425
         Jan         1385
         Mar         1420
Name: value, dtype: int64

## 2. 위에서 구한 결과 중, 매출 합계(Sales)가 1400을 초과하는 경우가 몇 건인지 구하시오.

In [92]:
print(total_Sales[total_Sales>1400].value_counts().sum())

6

In [93]:
print(len(total_Sales[total_Sales>1400]))

6