<a href="https://colab.research.google.com/github/SYWoo02/Engineer_BigData_Analysis_10/blob/main/Part2_%EC%9D%B4%EC%A7%84%EB%B6%84%EB%A5%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 이진분류 연습문제

## Section 3 신용카드 신청자의 미래 신용 예측
### 신용카드 신청자의 채무 불이행을 예측하시오.
### 학습용 데이터(train)를 이용해 새 일자리를 찾을지 예측하는 모델을 만든 후 이를 평가용 데이터(test)에 적용해 얻은 예측값을 다음과 같은 형식의 CSV 파일로 생성하시오
* 예측한 칼럼: STATUS(0: 채무 이행, 1: 채무 불이행)
* pred: 예측값
* 제출 파일명: 'result.csv'
* 제출한 모델의 성능은 f1 평가지표에 따라 채점한다.

In [1]:
# 라이브러리 및 데이터 불러오기
import pandas as pd

train = pd.read_csv("creditcard_train.csv")
test = pd.read_csv("creditcard_test.csv")

In [2]:
# EDA
print("===== Train 데이터 확인 =====")
print(train.head(5))
print("\n")

print("===== Test 데이터 확인 =====")
print(test.head(5))
print("\n")

print("===== 데이터 타입 확인 =====")
print(train.info(5))
print("\n")

print("===== Target의 분포 확인 =====")
print(train['STATUS'].value_counts())
print("\n")

print("===== Train 데이터 결측치 확인 =====")
print(train.isnull().sum())
print("\n")

print("===== Test 데이터 결측치 확인 =====")
print(test.isnull().sum())
print("\n")

===== Train 데이터 확인 =====
        ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5010092           F            N               N             0
1  5116701           M            N               Y             1
2  5069290           F            N               Y             0
3  5113315           F            Y               Y             0
4  5148853           M            Y               Y             0

   AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
0          225000.0  Commercial associate  Secondary / secondary special
1          112500.0  Commercial associate  Secondary / secondary special
2          270000.0  Commercial associate              Incomplete higher
3          153000.0               Working  Secondary / secondary special
4          261000.0               Working  Secondary / secondary special

  NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0            Married  House / apartment      -10304          -1682
1            Married  House / apartment      -10189          -1189
2            Married  House / apartment      -14783          -3397
3            Married  House / apartment      -19503         -10147
4            Married  House / apartment      -15708          -5250

   FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL        OCCUPATION_TYPE  \
0           1                0           0           0               Laborers
1           1                1           1           0                    NaN
2           1                0           0           0             Core staff
3           1                0           0           1  High skill tech staff
4           1                0           0           0               Laborers

   CNT_FAM_MEMBERS  STATUS
0              2.0       0
1              3.0       0
2              2.0       0
3              2.0       0
4              2.0       0


===== Test 데이터 확인 =====
        ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5037176           F            N               Y             1
1  5142150           M            Y               Y             0
2  5094889           F            N               Y             0
3  5137439           M            N               N             0
4  5148429           F            N               Y             0

   AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
0          337500.0  Commercial associate               Higher education
1          450000.0               Working  Secondary / secondary special
2           90000.0               Working               Higher education
3          225000.0               Working  Secondary / secondary special
4          135000.0  Commercial associate  Secondary / secondary special

     NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0  Single / not married  House / apartment      -14408           -431
1  Single / not married  House / apartment      -15960          -3574
2  Single / not married  House / apartment      -21532          -4630
3               Married  House / apartment       -9154          -1051
4        Civil marriage  House / apartment      -16891          -3332

   FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL        OCCUPATION_TYPE  \
0           1                0           0           0            Accountants
1           1                0           0           0  High skill tech staff
2           1                0           0           0               Laborers
3           1                0           1           0               Laborers
4           1                1           1           0                Drivers

   CNT_FAM_MEMBERS
0              2.0
1              1.0
2              1.0
3              2.0
4              2.0


===== 데이터 타입 확인 =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25519 entries, 0 to 25518
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   25519 non-null  int64
 1   CODE_GENDER          25519 non-null  object
 2   FLAG_OWN_CAR         25519 non-null  object
 3   FLAG_OWN_REALTY      25519 non-null  object
 4   CNT_CHILDREN         25519 non-null  int64
 5   AMT_INCOME_TOTAL     25519 non-null  float64
 6   NAME_INCOME_TYPE     25519 non-null  object
 7   NAME_EDUCATION_TYPE  25519 non-null  object
 8   NAME_FAMILY_STATUS   25519 non-null  object
 9   NAME_HOUSING_TYPE    25519 non-null  object
 10  DAYS_BIRTH           25519 non-null  int64
 11  DAYS_EMPLOYED        25519 non-null  int64
 12  FLAG_MOBIL           25519 non-null  int64
 13  FLAG_WORK_PHONE      25519 non-null  int64
 14  FLAG_PHONE           25519 non-null  int64
 15  FLAG_EMAIL           25519 non-null  int64
 16  OCCUPATION_TYPE      17543 non-null  object
 17  CNT_FAM_MEMBERS      25519 non-null  float64
 18  STATUS               25519 non-null  int64
dtypes: float64(2), int64(9), object(8)
memory usage: 3.7+ MB
None


===== Target의 분포 확인 =====
STATUS
0    25085
1      434
Name: count, dtype: int64


===== Train 데이터 결측치 확인 =====
ID                        0
CODE_GENDER               0
FLAG_OWN_CAR              0
FLAG_OWN_REALTY           0
CNT_CHILDREN              0
AMT_INCOME_TOTAL          0
NAME_INCOME_TYPE          0
NAME_EDUCATION_TYPE       0
NAME_FAMILY_STATUS        0
NAME_HOUSING_TYPE         0
DAYS_BIRTH                0
DAYS_EMPLOYED             0
FLAG_MOBIL                0
FLAG_WORK_PHONE           0
FLAG_PHONE                0
FLAG_EMAIL                0
OCCUPATION_TYPE        7976
CNT_FAM_MEMBERS           0
STATUS                    0
dtype: int64


===== Test 데이터 결측치 확인 =====
ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
dtype: int64

In [3]:
# train과 test 범주형 데이터 비교
cols = train.select_dtypes(include='object').columns
for col in cols:
  set_train = set(train[col])
  set_test = set(test[col])
  same = (set_train == set_test)
  if same:
    print(col,"\t카테고리 동일함")
  else:
    print(col,"\t카테고리 동일하지 않음")

CODE_GENDER 	카테고리 동일함
FLAG_OWN_CAR 	카테고리 동일함
FLAG_OWN_REALTY 	카테고리 동일함
NAME_INCOME_TYPE 	카테고리 동일함
NAME_EDUCATION_TYPE 	카테고리 동일함
NAME_FAMILY_STATUS 	카테고리 동일함
NAME_HOUSING_TYPE 	카테고리 동일함
OCCUPATION_TYPE 	카테고리 동일하지 않음

In [4]:
# 결측치 처리
train.dropna(subset=['OCCUPATION_TYPE'], inplace=True)

# Train에서 target 분리
target = train.pop('STATUS')

In [5]:
# 원-핫 인코딩
train = pd.get_dummies(train)
test = pd.get_dummies(test)

In [7]:
# Validation 데이터 분할
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.3, random_state=0)

# 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
score = f1_score(y_val, pred)
print("f1:", score)

f1: 0.2958579881656805

In [9]:
# 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

# 결과 파일 확인
submit = pd.read_csv("result.csv")
submit

      pred
0        0
1        0
2        0
3        0
4        0
...    ...
7586     0
7587     0
7588     0
7589     0
7590     0

[7591 rows x 1 columns]